### ISSUE TITLE
[Question] Link dead - teapot?

### ISSUE THREAD

**Issue by dalisoft** [f213/dotfiles#3]
Hi @f213, thanks for sharing your dotfiles and knowledge.

While checking links i found teapot link is dead (fisherman/teapot).
I called `brew info teapot`, gived `https://www.syntax-k.de/projekte/teapot/` link, i not sure it's right url or not, but decided to let you know about it.

Спасибо за труд =)

**Comment by f213** [comment]
Teapot was a theme i used to use couple of years ago. Now i use [nai](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#nai), so i just removed the stale link.

Thank you!

**Comment by dalisoft** [comment]
Nice. Have a nice day!
