### ISSUE TITLE
Вопрос: Замена ansible на Brewfile

### ISSUE THREAD

**Issue by mlnchk** [f213/dotfiles#6]
Привет!

Твой репозиторий и вебинары вдохновили на создание своего аналога.
Я даже начал изучать ansible, но в итоге понял, что все задачи, которые мне нужно через него сделать, покрываются командой `brew bundle` с лежащим в директории `Brewfile`. https://github.com/Homebrew/homebrew-bundle

Единственное отличие в твоем случае — роли для ансибла.
Собственно, мой вопрос в том, имеют ли эти роли какую-то ценность? Если нет, то и в ansible в таком случае нет смысла.

**Comment by f213** [comment]
Привет!

Помимо установки пакетов brew, роли ansible делают ещё кое-что: [настраивают](https://github.com/f213/dotfiles/blob/master/ansible/roles/productivity/tasks/main.yml#L39) системные параметры macos, [устанавливают](https://github.com/f213/dotfiles/blob/master/ansible/roles/productivity/meta/main.yml#L2) кучу софта из appstore

**Comment by mlnchk** [comment]
Через Brewfile можно ставить аппы из appstore с помощью `mas`, [вот так](https://github.com/mlnchk/dotfiles/blob/master/Brewfile#L25-L27).

А системные настройки можно ставить обычным shell скриптом, [вот так](https://github.com/mlnchk/dotfiles/blob/master/scripts/macos-settings.sh).

В любом случае, каждому свое, мне было просто интересно, стоит ли усложнять конфиг ансиблом в моем случае и оказалось, что нет. А тебе спасибо за ответ и вдохновение 🙂
